[#7142] Add db backward compatibility in backend
imbf/pinpoint pull request #10
Opened 2020-09-02 12:59 UTC by imbf

1. Create insertRuleExceptWebhookSend and updateRuleExceptWebhookSend query for changed table schema backward compatibility
2. update DB Service Logic
3. Add webhookEnable Property in ConfigProperties
4. Update Configuration Api for webhook

2020-09-03 10:31 UTC, cwJohnPark requested changes
리뷰 확인 부탁드립니다.

2020-09-03 10:31 UTC, cwJohnPark commented on web/src/main/resources/batch-root.properties
> +#job.cleanup.inactive.agents.duration.days=
이것은 원래 있던건데 추가하신건가요?

2020-09-03 10:31 UTC, cwJohnPark commented on web/src/main/java/com/navercorp/pinpoint/web/config/ConfigProperties.java
> +
공백 발견!

2020-09-03 10:31 UTC, cwJohnPark commented on web/src/main/resources/mapper/AlarmMapper.xml
> +    <insert id="insertRule" parameterType="Rule" useGeneratedKeys="true" keyProperty="ruleId">
최종 PR될 때는 insertRule은 그대로이니 insertRule은 수정되지 않아야 하지 않을까요?

2020-09-03 10:59 UTC, imbf reviewed
리뷰 감사합니다!! 바로 변경 사항 커밋 날릴 예정입니다!

2020-09-03 10:59 UTC, imbf commented on web/src/main/java/com/navercorp/pinpoint/web/config/ConfigProperties.java
> +
개행문자가 LF면 해당 변경사항이 맞지 않나요 ㅎㅎ? (궁금)

2020-09-03 10:59 UTC, imbf commented on web/src/main/resources/batch-root.properties
> +#job.cleanup.inactive.agents.duration.days=
아뇨 ㅎㅎ 자꾸 추가되더라구요.. 반영하겠습니다

2020-09-03 10:59 UTC, imbf commented on web/src/main/resources/batch-root.properties
> +#job.cleanup.inactive.agents.duration.days=
![Screen Shot 2020-09-03 at 7 51 53 PM](https://user-images.githubusercontent.com/47495187/92106203-0431f080-ee1f-11ea-9bd7-1c1c22fb66c9.png)
해당 Preference 때문에 생긴 변경사항 인 것 같습니다.

2020-09-03 10:59 UTC, imbf commented on web/src/main/resources/mapper/AlarmMapper.xml
> +    <insert id="insertRule" parameterType="Rule" useGeneratedKeys="true" keyProperty="ruleId">
insertRule은 그대로여야만 하는 이유가 있을까요???

저희는 추후에 계속 webhook이 있는 기능으로 pinpoint-web을 서비스할 것이기 때문에 Rule을 insert하는 쿼리인
insertRule은 하위 호환을 위한 쿼리가 아니라, webhook 기능이 추가된 버전(추후 계속 사용)을 위한 쿼리로써 변경되야 한다고 생각합니다.

즉, insertRule 자체도 webhook기능이 추가됨에 따라 바뀌어야만 하고, DB 하위 호환을 보장하기 위한 쿼리가 하나더 생겨야 한다고 생각합니다.

2020-09-03 11:48 UTC, cwJohnPark commented on web/src/main/java/com/navercorp/pinpoint/web/config/ConfigProperties.java
> +
아 그렇네요 ㅋㅋ

2020-09-03 11:56 UTC, cwJohnPark commented on web/src/main/resources/mapper/AlarmMapper.xml
> +    <insert id="insertRule" parameterType="Rule" useGeneratedKeys="true" keyProperty="ruleId">
insertRule을 최신으로 올리고 이전 버전을 새로 생성하셨군요.
종진님의 의견을 존중합니다 👍

2020-09-03 12:15 UTC, imbf commented on web/src/main/resources/mapper/AlarmMapper.xml
> +    <insert id="insertRule" parameterType="Rule" useGeneratedKeys="true" keyProperty="ruleId">
좋은 질문 해주셔서 감사합니다 ㅎㅎ

2020-09-04 12:11 UTC, doll6777 requested changes

2020-09-04 12:28 UTC, doll6777 commented on web/src/main/java/com/navercorp/pinpoint/web/service/AlarmServiceImpl.java
> +        if (!rule.isWebhookSend()) {
그외에는 괜찮아보입니다. 수고하셨어요

2020-09-04 14:23 UTC, imbf commented on web/src/main/java/com/navercorp/pinpoint/web/service/AlarmServiceImpl.java
> +        if (!rule.isWebhookSend()) {
넵 감사합니다.

2020-09-04 14:32 UTC, imbf commented
코드 리뷰를 위한 PR이기 때문에 코드 리뷰가 끝났음으로 PR Close

2020-09-04 14:32 UTC, closed without merging