[#7142] Add db backward compatibility
imbf/pinpoint pull request #13
Opened 2020-09-05 06:21 UTC by imbf

1. **이전 버젼(webhook기능 지원 이전)의 pinpoint 사용자**

   - 기존 SMS, Email 전송 타입만 제공할 때 부터 pinpoint-web을 사용한 User를 가르킨다.
   - webhook의 기능을 사용하고 싶다면
     백과 프론트를 webhook 기능이 존재하는 버젼으로 업데이트하고, webhook.enable = true로 설정, webhook.receiver.url 입력, DB alarm_rule 테이블에 webhook_send 컬럼 추가
     - 이전 버젼의 DB 사용자(alarm_rule 테이블에 webhook_send 컬럼 존재 x)를 위해 하위 호환 쿼리를 만들었다.
       webhook.enable로써 테이블의 스키마 변경을 구분하며, 이를 통해 DB Service 단에서 적절한 쿼리 호출을 위한 분기를 진행한다.
   - 여러 설정을 마치고 webhook의 기능을 사용한 사용자가 사용도중 webhook.enable=false로 설정하게 되면 front단에서는 어떻게 보여 줄 것인가?
     - webhook.enable로서 front의 alarm_list, alarm_create_update_form에 webhook을 적용할지 안할지 구분했다.
     - webhook.enable=false 시, front의 alarm_list와 alarm_create_update_form에서는 webhook을 볼 수 없다.
       (DB에 저장된 해당 Rule의 webhook_send 값이 true이더라도, webhook.enable=false로 설정한 사용자는 해당 데이터의 webhook_send의 값을 프론트에서 변경할 수 도 볼 수 도 없다.)  => SMS, Email 전송 타입만 프론트에서 보여지고 수정할 수 있다.
     - webhook.enable=true 시, front단에서 alarm_list와 alarm_create_update_form에서는 webhook_send 컬럼의 값을 볼 수 있게 되고, 수정할 수 있게 된다.
   - webhook.enable=false로 설정하게 되면 batch작업시 webhook Sender 또한 동작을 멈출 것이다.

2. **처음부터 webhook_send 기능이 있는 pinpoint 버젼 사용자.**

   - 프론트, 백, DB모두 webhook 기능을 사용하기에 적절한 버젼을 사용하는 유저를 가리킨다.
   - 위의 유저가 webhook.enable=false로 설정할 경우
     - webhook.enable로서 front의 alarm_list, alarm_create_update_form에 webhook을 적용할지 안할지 구분했다.
     - webhook.enable=false 시, front의 alarm_list와 alarm_create_update_form에서는 webhook을 볼 수 없다.
       (DB에 저장된 해당 Rule의 webhook_send 값이 true이더라도, webhook.enable=false로 설정한 사용자는 해당 데이터의 webhook_send의 값을 프론트에서 변경할 수 도 볼 수 도 없다.)  => SMS, Email 전송 타입만 프론트에서 보여지고 수정할 수 있다.
     - webhook.enable=true 시, front단에서 alarm_list와 alarm_create_update_form에서는 webhook_send 컬럼의 값을 볼 수 있게 되고, 수정할 수 있게 된다.
   - webhook.enable=false로 설정하게 되면 batch작업시 Sender또한 동작을 멈출 것이다.

### **아래의 그림은 webhook.enable = false / true에 따른 프론트에서 동일한 데이터를 어떠한 방식으로 보여주는지에 대한 그림이다.**

**webhook.enable = false**

- alarm_rule 테이블에 webhook_send의 값에 관계없이 webhook은 alarm_list에 보이지 않는다.
  webhook Type의 Alarm도 생성할 수 없을 뿐더러 특정 alarm의 Type 변경시 webhook이 포함된 타입으로 변경할 수 없다.

<img width="1680" alt="Screen Shot 2020-09-05 at 12 18 14 PM" src="https://user-images.githubusercontent.com/47495187/92297376-a82faf00-ef79-11ea-8727-70cf11a6aaec.png">

**webhook.enable = true** 

- alarm_rule 테이블에 webhook_send의 값이 true일경우, alarm list에 해당 값이 보일 뿐더러, Type이 webhook인 alarm을 생성 및 수정 가능하다.

<img width="1680" alt="Screen Shot 2020-09-05 at 12 19 20 PM" src="https://user-images.githubusercontent.com/47495187/92297381-b087ea00-ef79-11ea-9990-2d12ccde4f7e.png">

2020-09-07 10:59 UTC, doll6777 requested changes

2020-09-07 10:59 UTC, doll6777 commented on web/src/main/java/com/navercorp/pinpoint/web/controller/ConfigController.java
> +        result.put("webhookEnable", webProperties.isWebhookEnable());
여기서 가져오는 프로퍼티가 pinpoint-web-root.properties 라고 했던거 같은데  
batch-root.properties 에 있는 프로퍼티도 가져올수 있나요?~

2020-09-07 11:45 UTC, doll6777 commented on web/src/main/angular/src/app/core/components/alarm-rule-list/alarm-rule-list.component.ts
>              : !emailSend && smsSend ? 'SMS'
웹훅이 생겨서 가독성이 좀 안좋아 진것같은데 이런 방법은 어떨까요?
```
            const sendChannels = [];
            if (emailSend) {
                sendChannels.push('Email');
            }
            if (smsSend) {
                sendChannels.push('SMS');
            }
            if (webhookSend) {
                sendChannels.push('Webhook');
            }
            if (!sendChannels) {
                sendChannels.push('None');
            }
            return sendChannels.join(', ');
```

2020-09-07 11:50 UTC, doll6777 commented on web/src/main/angular/src/app/core/components/alarm-rule-list/alarm-rule-list.component.ts
>              : !emailSend && smsSend ? 'SMS'
webhook이 추가되어서 가독성이 조금 안좋아 진것같은데 이런 방법은 어떨까요??
```
           const sendChannels = [];
            if (emailSend) {
                sendChannels.push('Email');
            }
            if (smsSend) {
                sendChannels.push('SMS');
            }
            if (webhookSend) {
                sendChannels.push('Webhook');
            }
            if (sendChannels.length === 0) {
                sendChannels.push('None');
            }
            return sendChannels.join(', ');
```

2020-09-07 11:57 UTC, doll6777 commented on web/src/main/java/com/navercorp/pinpoint/web/config/ConfigProperties.java
> +    @Value("${webhook.enable}")
@Value("${webhook.enable:false}") 로 초기값이있으면 좋을것같습니다.

2020-09-07 12:31 UTC, imbf reviewed
코멘트 남겼습니다!! 좋은 의견 감사드려요

2020-09-07 12:31 UTC, imbf commented on web/src/main/java/com/navercorp/pinpoint/web/config/ConfigProperties.java
> +    @Value("${webhook.enable}")
네!! 알겠습니다 좋은 의견 감사드려요

2020-09-07 12:31 UTC, imbf commented on web/src/main/java/com/navercorp/pinpoint/web/controller/ConfigController.java
> +        result.put("webhookEnable", webProperties.isWebhookEnable());
```
 <bean id="webPropertyConfigurer" class="org.springframework.context.support.PropertySourcesPlaceholderConfigurer">
        <property name="locations">
            <list>
                <value>classpath:hbase-root.properties</value>
                <value>classpath:jdbc-root.properties</value>
                <value>classpath:pinpoint-web-root.properties</value>
                <value>classpath:batch-root.properties</value>
                <!-- override configuration -->
                <value>classpath:profiles/${pinpoint.profiles.active}/hbase.properties</value>
                <value>classpath:profiles/${pinpoint.profiles.active}/jdbc.properties</value>
                <value>classpath:profiles/${pinpoint.profiles.active}/pinpoint-web.properties</value>
                <value>classpath:profiles/${pinpoint.profiles.active}/batch.properties</value>
                <!-- external property for override -->
                <value>file:#{ systemProperties['pinpoint.web.config.location'] ?: '-Dpinpoint.web.config.location does not set' }</value>
            </list>
        </property>
```
설정에 의해서 web-root.properties와 batch-root.properties상관 없이 아주 잘 프로퍼티를 가져올 수 있네요

2020-09-07 12:31 UTC, imbf commented on web/src/main/angular/src/app/core/components/alarm-rule-list/alarm-rule-list.component.ts
>              : !emailSend && smsSend ? 'SMS'
가독성이 안좋은 것은 인정합니다.. ㅜㅜ

좋은 방법으로 한번 바꾸어 보죠!! 좋은 의견 감사합니다.

2020-09-07 12:52 UTC, imbf commented
리뷰 반영 했습니다.

2020-09-08 02:07 UTC, doll6777 commented on web/src/main/java/com/navercorp/pinpoint/web/alarm/SpringWebhookSender.java
> +        this.webhookEnable = batchConfiguration.isWebhookEnable();
이 브랜치 최신으로 리베이스 해서 창원님 테스트코드 넣고,
테스트코드의 컴파일 오류 해결한  커밋 푸시하는거 어떤가요?
```
git checkout add-db-backward-compatibility
git rebase add-alarm-webhook
```
제가 하려고하니깐 권한이 읎어서 Imbf에 푸시를 못하네용..

2020-09-08 04:40 UTC, imbf commented on web/src/main/java/com/navercorp/pinpoint/web/alarm/SpringWebhookSender.java
> +        this.webhookEnable = batchConfiguration.isWebhookEnable();
권한 드리겠습니다.

2020-09-08 04:41 UTC, imbf commented on web/src/main/java/com/navercorp/pinpoint/web/alarm/SpringWebhookSender.java
> +        this.webhookEnable = batchConfiguration.isWebhookEnable();
혜란님 초대 보냈는데 수락을 안하신것 같아요!! Pending상태네요

2020-09-08 12:36 UTC, merged