Fix sender
imbf/pinpoint pull request #18
Opened 2020-09-14 14:00 UTC by doll6777

- add vo sender package 
- arrange Rule getter/setter method
- change method naming triggerWebhook -> sendWebhook
- arrange webhookEnable check method in WebhookSender 
- change class naming SpringWebhookSender -> WebhookSenderImpl
- add email,phonenumber,countrycode to UserMember

2020-09-15 04:19 UTC, imbf requested changes
UserMember 관련 리뷰 하나 남겨드렸습니다!!

고생 많으셨어요~~

2020-09-15 04:19 UTC, imbf commented on web/src/main/java/com/navercorp/pinpoint/web/alarm/WebhookSenderImpl.java
> +            })).collect(Collectors.toList());
추후 webhook 기능의 확장성을 위해서 UserGroupMember 도메인 데이터만 전송하기에는 확장성이 부족하기 때문에
우리는 User 도메인에 대한 데이터 전송이 필요한데, UserGroupService를 통해, UserGroupMember List를 가져오고 userGroupMember Id를 인자로 사용해 UserService의 메소드를 호출해서 User를 가져오는 것은 너무 비효율 적인 것 같아요!!

내부적으로 UserGroupMember List를 가져오는 곳에서 Select query가 한번 발생하고, UserGroup List의 각 Element를 User로 Mapping시에 Element 하나당 query가 한번씩 총 n번이 발생되 적절하지 못한 것 같네요!!

관련 Mapper 문과 DB 스키마를 보시면 Select + Join 쿼리 한번으로써, User List를 가져올 수 있을 것 같아요!!

또한 해당 쿼리를 적절히 Dao와 Service단으로 빼내면 불필요한 코드를 많이 줄일 수 있을 것 같아요!!

2020-09-15 10:34 UTC, cwJohnPark reviewed
리뷰 완료 하였습니다 ~

2020-09-15 10:34 UTC, cwJohnPark commented on web/src/main/java/com/navercorp/pinpoint/web/alarm/WebhookSenderImpl.java
> +    private UserMember toUserMember(User user) {
캡슐화를 지키기 위해서, UserMember 생성은 UserMember에서 스태틱 팩토리 메소드를 만들어서 하는 것이 좋을 것 같습니다.
그리고 UserMember의 setter는 다른 곳에서 필요하지 않으니 없애는 것도 좋다고 생각합니다. 
getter는 Json 직렬화시 필요합니다.

2020-09-15 14:31 UTC, doll6777 commented on web/src/main/java/com/navercorp/pinpoint/web/alarm/WebhookSenderImpl.java
> +            })).collect(Collectors.toList());
넵 이부분도 고려했었는데 기존에 존재하는 vo를 수정하지 않는 방향으로 가려고 하다보니 그렇게 작성하였습니다.

말씀하신대로,
저희가 필요한부분은 userGroupId에 해당하는 멤버정보리스트라 
기존 UserGroupMember vo에 메일,핸드폰번호도 가져오도록 쿼리를 수정하였고 
프론트쪽에서도 받는부분 수정하고, 동작 확인하였습니다.

2020-09-15 14:33 UTC, doll6777 commented on web/src/main/java/com/navercorp/pinpoint/web/alarm/WebhookSenderImpl.java
> +    private UserMember toUserMember(User user) {
UserMember가 UserGroupMember를 알지는 않는것이 좋을것같아서 setter를 없애고 생성자로 만들어 반영했습니다.
의견 감사드립니다~

2020-09-15 15:05 UTC, doll6777 commented on web/src/main/java/com/navercorp/pinpoint/web/alarm/WebhookSenderImpl.java
> +    private UserMember toUserMember(User user) {
팩토리 메서드 사용했더니 가독성도 좋아졌네요
좋은 의견 감사합니다.

2020-09-16 02:45 UTC, imbf commented on web/src/main/java/com/navercorp/pinpoint/web/alarm/WebhookSenderImpl.java
> +            })).collect(Collectors.toList());
기존에 존재하는 vo를 수정하지 않고도 DB 쿼리문을 줄일 수 있지 않을까요???

UserMember의 필드들이 User 도메인 필드의 부분집합 이기 때문에 Rule의 GroupId를 인자로 사용해 DB로부터 User List를 가져와서 UserMember로 Mapping 시켜줘도 될 것 같은데요 ㅎㅎ?

2020-09-16 03:32 UTC, doll6777 commented on web/src/main/java/com/navercorp/pinpoint/web/alarm/WebhookSenderImpl.java
> +            })).collect(Collectors.toList());
웹훅의 UserMember로 매핑시켜주는 쿼리를 새로 만들자는 말씀이신가요?

저희가 원하는것이 userGoupId에 해당하는 유저정보 리스트를 가져오는것인데,
웹훅을 위해 새로운 쿼리를 작성하는것보다는,
그게 기존에 있던 "selectMemberList"에 필요한 유저정보를 추가하는것이 더 좋다고 생각합니다.

2020-09-16 03:39 UTC, doll6777 commented on web/src/main/java/com/navercorp/pinpoint/web/alarm/WebhookSenderImpl.java
> +            })).collect(Collectors.toList());
도메인상 groupId에 해당하는 멤버가 "UserMember"로 사용되고 있는데,
UserMember에 필요한 필드를 가져올수있도록 추가하는게 더 자연스럽지 않을까 생각합니다.

2020-09-16 05:56 UTC, imbf commented on web/src/main/java/com/navercorp/pinpoint/web/alarm/WebhookSenderImpl.java
> +            })).collect(Collectors.toList());
저는 최대한 VO 변경없이 쿼리만 추가해서 데이터를 가져오자는 생각으로 말씀 드렸는데
혜란님의 관점에서 생각해 보니 더 맞는 방향인 것 같네요!!

UserGroupMember에 필요한 인스턴스 필드를 추가해서 데이터를 가져오는게 더 자연스러운 것 같아요!!
또 다른 관점에서 생각해 볼 수 있엇네요 감사함돠~

2020-09-16 09:21 UTC, imbf commented
머지 하겠슴돠~

2020-09-16 09:21 UTC, merged

2020-09-22 09:32 UTC, doll6777 commented on web/src/main/angular/src/app/core/components/group-member/group-member-data.service.ts
> +    email: string;
넵 수정하겠습니다.

2020-09-22 09:32 UTC, doll6777 commented on web/src/main/java/com/navercorp/pinpoint/web/vo/UserGroupMember.java
> +    private String email;
이부분 고려할 때는 UserGroupMember가 그룹아이디로 가져온 멤버의 의미를 더 잘 담을것 같아서 그렇게 결정하였습니다.
그것보다는 User로 select하여 UserService에서 가져오는것이 더 자연스럽다면 
반영해놓도록 하겠습니다.