[#7142] remove checker-type header, send userGroupMembers
imbf/pinpoint pull request #8
Opened 2020-08-29 08:13 UTC by doll6777

reciever server에서 받은 페이로드

```
{"pinpointUrl":"","batchEnv":"release","sequenceCount":22,"applicationId":"TESTAPP","checkerName":"SYSTEM CPU USAGE RATE","threshold":1,"notes":"","checkerValue":{"unit":"%","agentValues":{"test-agent":33}},"userGroupMembers":[{"number":null,"userGroupId":"usergroup1","memberId":"ranran","name":"ran","department":"dep"}]}
```

2020-08-30 03:01 UTC, imbf reviewed
간단하게 리뷰 남겨 드렸구요!! 

저또한 마찬가지로 Payload 재설계 진행해보겠습니다.

2020-08-30 03:01 UTC, imbf commented on web/src/main/java/com/navercorp/pinpoint/web/alarm/vo/WebhookPayload.java
> -    private String userGroupId;
혹시 userGroupId 인스턴스 변수를 삭제하신 이유는 따로 있을까요???

webhook 메시지를 Receiver Server에서 특정 그룹마다 활용하기 위해 UserGroupMember List에 직접 접근해서, User별 UserGroupId를 참조하는 것보다, UserGroupMember List와 별개로 UserGroupId 데이터를 넘겨주는게 좀 더 좋다고 생각되네요!

@doll6777 님의 의견은 어떠신가요?

2020-08-30 06:23 UTC, cwJohnPark commented on web/src/main/java/com/navercorp/pinpoint/web/alarm/vo/WebhookPayload.java
> -    private String userGroupId;
User group Id만 넘기면 유저에 대해 어떻게 알 수 있을까요?

2020-08-30 06:28 UTC, imbf commented on web/src/main/java/com/navercorp/pinpoint/web/alarm/vo/WebhookPayload.java
> -    private String userGroupId;
UserGroupMember List와 별개로 UserGroupId를 추가적으로 넘겨줘야 된다고 생각해서 말씀드렸습니다욥

2020-08-30 07:12 UTC, doll6777 commented on web/src/main/java/com/navercorp/pinpoint/web/alarm/vo/WebhookPayload.java
> -    private String userGroupId;
웹훅을 받는 입장에서 꼭 필요한 정보만 넘겨야 하지 않을까요?
```json
   "userGroupMembers":[
      {
         "number":null,
         "userGroupId":"usergroup1",
         "memberId":"ranran",
         "name":"ran",
         "department":"dep"
      }
   ]
```
그룹 멤버 리스트에 보면 이미 userGroupId가 포함되어 잇어서 중복되는 정보일 것 같아요.

2020-08-30 08:07 UTC, imbf commented on web/src/main/java/com/navercorp/pinpoint/web/alarm/vo/WebhookPayload.java
> -    private String userGroupId;
중복되는 정보인 걸 알고 있음에도
이를 받아서 사용할 Receiver Server의 입장에서는 UserGroupId가 있을 경우가 훨씬 편하다고 생각했습니다.

UserGroupMember List의 특정 User만 보고 모든 User가 해당 userGroupId에 포함되어 있다는 걸 추측하기에는 조금 무리가 있다는 생각도 되네요.

오히려 이를 대표해주는 UserGroupId가 존재해야 더 좋은 Json Data일 것 같아요.

2020-08-30 08:12 UTC, doll6777 commented on web/src/main/java/com/navercorp/pinpoint/web/alarm/vo/WebhookPayload.java
> -    private String userGroupId;
```List<UserGroupMember> userGroupMembers = userGroupService.selectMember(checker.getRule().getUserGroupId());```

근데 해당 유저그룹멤버 리스트는 룰에 해당하는 그룹아이디에 해당하는 멤버들인데..
그래서 유저 아이디가 모두 같을거 같은데요
그래도 필요한가용??

2020-08-30 08:16 UTC, imbf commented on web/src/main/java/com/navercorp/pinpoint/web/alarm/vo/WebhookPayload.java
> -    private String userGroupId;
오히려 모두 같다면 모두 같은 유저아이디의 데이터를 삭제하고 대표 유저아이디 하나만 놓는게 더 좋지 않을까요 ㅋㅋ?

2020-08-30 08:17 UTC, cwJohnPark commented on web/src/main/java/com/navercorp/pinpoint/web/alarm/vo/WebhookPayload.java
> -    private String userGroupId;
그럼 userGroupMembers의 userGroupId를 밖으로 빼내면 되지 않을까요? API 명세야 실제 도메인과는 형태가 다른 일이 비일비재하니까요.

2020-08-30 08:17 UTC, imbf commented on web/src/main/java/com/navercorp/pinpoint/web/alarm/vo/WebhookPayload.java
> -    private String userGroupId;
관련 DTO를 만들어도 좋을것 같은데요

2020-09-01 13:20 UTC, doll6777 commented on web/src/main/java/com/navercorp/pinpoint/web/alarm/vo/WebhookPayload.java
> -    private String userGroupId;
@imbf @cwJohnPark 관련해서 페이로드 만들어 수정했으니 확인바랍니다. 네이밍 좋은 의견 있으면 부탁 드립니다~

2020-09-03 08:25 UTC, imbf approved these changes
수고하셨습니다!! 혜란님!!

2020-09-03 10:52 UTC, cwJohnPark requested changes
리뷰 확인 바랍니다.

2020-09-03 10:52 UTC, cwJohnPark commented on web/src/main/java/com/navercorp/pinpoint/web/alarm/SpringWebhookSender.java
> +
생성자에서 userGroupMemberPayload 를 받는게 더 안전하지 않을까요?
```java
List<UserMember> userMembers = userGroupService.selectMember(checker.getRule().getUserGroupId())
                    .stream()
                    .map((UserMember::new))
                    .collect(Collectors.toList());
            UserGroupMemberPayload userGroupMemberPayload = new UserGroupMemberPayload(checker.getRule().getUserGroupId(), userMembers);
            
            WebhookPayload webhookPayload = new WebhookPayload(checker, batchConfiguration, sequenceCount, userGroupMemberPayload);
```

2020-09-03 10:52 UTC, cwJohnPark commented on web/src/main/java/com/navercorp/pinpoint/web/alarm/vo/WebhookPayload.java
> -    private String userGroupId;
UserGroupMemberPayload 괜찮을 것 같습니다~

2020-09-04 12:19 UTC, doll6777 commented on web/src/main/java/com/navercorp/pinpoint/web/alarm/SpringWebhookSender.java
> +
넵 그러네요 반영했습니다~

2020-09-05 01:25 UTC, imbf commented
혜란님 add-alarm-webhook branch로 PR 부탁드려도 될까요 ㅎㅎ? (혜란님이 작업하신 변경사항 commit만)

2020-09-05 14:09 UTC, closed without merging