[#7142] Add checkerType instance field in webhookPayload
imbf/pinpoint pull request #9
Opened 2020-08-30 05:41 UTC by imbf

webhook Message Header에 CheckerType을 주는 방식에서 Body에 CheckerType을 주는 방식으로의 변환을

"어떻게 하면 instance of를 사용하지 않고 적절한 객체에게 해당 책임을 줄 수 있을까?" 에 대한 고민과 함께 webhookPayload를 재설계 하였습니다.

리뷰 부탁드립니다.

2020-08-30 06:22 UTC, cwJohnPark requested changes

2020-08-30 06:22 UTC, cwJohnPark commented on web/src/main/java/com/navercorp/pinpoint/web/alarm/vo/WebhookPayload.java
> +    private String checkerType;
String 보다 Enum으로 만드는 게 어떨까요?

2020-08-30 06:26 UTC, imbf commented on web/src/main/java/com/navercorp/pinpoint/web/alarm/vo/WebhookPayload.java
> +    private String checkerType;
좋습니다 ㅎㅎ

2020-08-30 07:32 UTC, imbf commented on web/src/main/java/com/navercorp/pinpoint/web/alarm/vo/WebhookPayload.java
> +    private String checkerType;
혹시 enum을 사용하고 싶으신 이유가 따로 있을까요??

2020-08-30 07:35 UTC, doll6777 reviewed
받는쪽에서 checkerType에 따라 파싱하는거랑
전에 얘기 나왔었던
```
agentCheckvalues:
alarmCheckvalues:
```
필드 따로 두는거에 비해 어떻게 차이가 있을까요? 별 차이 없나요?

2020-08-30 07:35 UTC, doll6777 commented on web/src/main/java/com/navercorp/pinpoint/web/alarm/vo/WebhookPayload.java
> +        checkerType = checker.getCheckerType();
얘도 똑같이 this  붙여주시면 좋을것같네요

2020-08-30 07:56 UTC, imbf commented on web/src/main/java/com/navercorp/pinpoint/web/alarm/vo/WebhookPayload.java
> +    private String checkerType;
![image](https://user-images.githubusercontent.com/47495187/91654174-be54ef80-eae1-11ea-8267-be0dc2550049.png)

2020-08-30 07:58 UTC, imbf commented on web/src/main/java/com/navercorp/pinpoint/web/alarm/vo/WebhookPayload.java
> +        checkerType = checker.getCheckerType();
네넹

2020-08-30 08:00 UTC, imbf commented on web/src/main/java/com/navercorp/pinpoint/web/alarm/vo/WebhookPayload.java
> +        checkerType = checker.getCheckerType();
webhookSend에서 checkerType에 따라 파싱해서 webhookPayload에 checkerType을 설정하는 것을 말씀하신 걸까요??

2020-08-30 08:24 UTC, imbf commented on web/src/main/java/com/navercorp/pinpoint/web/alarm/vo/WebhookPayload.java
> +        checkerType = checker.getCheckerType();
doll6777님과 같이 한다면 두 필드중 하나는 null이 생기겠네요!!

2020-08-30 08:27 UTC, doll6777 commented on web/src/main/java/com/navercorp/pinpoint/web/alarm/vo/WebhookPayload.java
> +        checkerType = checker.getCheckerType();
전에멘토님이 알려주셧던게 필드따로두는방법 이었던거같아서요 체커타입이라는거 따로안넣구

2020-08-30 08:46 UTC, imbf commented on web/src/main/java/com/navercorp/pinpoint/web/alarm/vo/WebhookPayload.java
> +        checkerType = checker.getCheckerType();
아하 체커타입이 멘토님이 알려주셨던 방법이 아니었나요???

2020-08-31 00:19 UTC, doll6777 commented on web/src/main/java/com/navercorp/pinpoint/web/alarm/vo/WebhookPayload.java
> +        checkerType = checker.getCheckerType();
두개 알려주셨던거같아요
처음에 알려주신게 체커타입,
두번쨰가 필드따로넣는거 ㅎㅎ

2020-08-31 01:11 UTC, imbf commented on web/src/main/java/com/navercorp/pinpoint/web/alarm/vo/WebhookPayload.java
> +        checkerType = checker.getCheckerType();
아하 그렇군요!!

agentCheckvalues
alarmCheckvalues

위의 필드를 payload에  넣는다면 한 필드에는 null이 발생할 텐데 위의 방법을 사용하고 싶은 이유가 있을까요?

2020-08-31 09:55 UTC, doll6777 commented on web/src/main/java/com/navercorp/pinpoint/web/alarm/vo/WebhookPayload.java
> +        checkerType = checker.getCheckerType();
사용하고싶은건 아니고 두가지 방법이 있는데 하나 선택한 이유를 질문한거에요~
체커타입도 어차피 타입에따라 if 분기타서 파싱하는거라 비슷할것같긴해요

2020-08-31 09:58 UTC, imbf commented on web/src/main/java/com/navercorp/pinpoint/web/alarm/vo/WebhookPayload.java
> +        checkerType = checker.getCheckerType();
아하 그렇다면 null 을 없애는 방향인 체커타입 제공으로 가도 될까요??

2020-08-31 10:24 UTC, imbf commented on web/src/main/java/com/navercorp/pinpoint/web/alarm/vo/WebhookPayload.java
> +        checkerType = checker.getCheckerType();
webhook message에 2개의 checker value 중 하나의 checker value가 null인 것을 사용해서 해당 message가 특정한 checker 관련 값을 갖는 것을 알려주는 것보다 type을 알려주고 대응하는 checker value를 알려주는게 조금 더 명시적일 것 같다는 생각도 드네요 ㅎㅎ

또한 null을 기반으로 분기를 타는 것 보다는 checker type을 기반으로 분기를 타는 게 조금 더 예외를 줄일 수 있는 방법 일 것 같다고 생각하네요 ㅎㅎ(사실 비슷하다..)

2020-08-31 12:35 UTC, imbf commented on web/src/main/java/com/navercorp/pinpoint/web/alarm/vo/WebhookPayload.java
> +        checkerType = checker.getCheckerType();
분기문만 보면 Value를 null로써 구분해서 분기를 태우는 방법과 CheckerType으로써 구분해서 분기를 태우는 방법 둘다 비슷하지만, 

if(AgentCheckerValue == null) 보다는 if(CheckerType == AlarmChecker)로써 분기하는게 더 좋다는게 제 생각입니다요 ㅎㅎ

2020-09-01 11:08 UTC, merged